version: 1
enabled: true
plugins:
  job_runtime:
    enabled: true
  static_hosting:
    merged-test-coverage:
      metadata:
        name: Test coverage report
      path: coverage/merged/lcov-report
    storybook:
      metadata:
        name: Storybook
      path: storybook-static
    cypress-video:
      metadata:
        name: Cypress video
      path: cypress/videos/spec.js.mp4
